import { ClerkProvider } from '@clerk/nextjs'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import BG from '@/public/homeBG.jpg'
import Image from 'next/image'
import { Raleway } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={raleway.className}>
        <Image src={BG} alt='bg' className='absolute lg:object-fit object-cover w-full lg:h-[600px] h-[50%] brightness-50 z-0 rounded-b-lg'/>
              <NavBar />
              {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
